"use client";
import { useState } from "react";
import { categories,products,type Category } from "./products";
import { useCart } from "@/features/cart/cart";
export function Storefront(){const [category,setCategory]=useState<"Todos"|Category>("Todos");const [open,setOpen]=useState(false);const cart=useCart();const shown=category==="Todos"?products:products.filter(p=>p.category===category);return <main>
<header className="nav"><a className="brand" href="#">NFC<span>Tapeador</span></a><button className="cartButton" onClick={()=>setOpen(true)}>Carrito <b>{cart.count}</b></button></header>
<section className="hero"><div className="eyebrow">TECNOLOGÍA QUE CONECTA</div><h1>Un toque.<br/><span>Una historia.</span></h1><p>Productos NFC personalizados que convierten objetos cotidianos en experiencias digitales útiles, memorables y fáciles de compartir.</p><a href="#catalogo" className="primary">Explorar productos →</a><div className="orb"><div className="nfc">)))</div><small>ACERCA TU CELULAR</small></div></section>
<section className="catalog" id="catalogo"><div className="sectionTitle"><div><small>CATÁLOGO</small><h2>Encuentra tu NFC</h2></div><p>Elige una categoría y descubre lo que podemos crear para ti.</p></div><div className="filters">{categories.map(c=><button key={c} className={category===c?"active":""} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="grid">{shown.map((p,i)=><article className="card" key={p.id} style={{animationDelay:`${i*70}ms`}}><div className="visual"><span>{p.emoji}</span><i>NFC</i></div><div className="cardBody"><small>{p.category}</small><h3>{p.name}</h3><p>{p.description}</p><div className="cardFoot"><strong>Consultar</strong><button onClick={()=>{cart.add(p);setOpen(true)}}>Agregar +</button></div></div></article>)}</div></section>
<section className="promise"><small>¿POR QUÉ NFC TAPEADOR?</small><h2>Diseñado para conectar<br/>el mundo físico con el digital.</h2><div><p><b>⚡ Instantáneo</b><br/>Sin apps. Solo acerca el celular.</p><p><b>✦ Personalizable</b><br/>Diseño y contenido pensado para ti.</p><p><b>↻ Actualizable</b><br/>Cambia la información sin cambiar el NFC.</p></div></section>
{open&&<><div className="shade" onClick={()=>setOpen(false)}/><aside className="drawer"><div className="drawerHead"><h2>Tu carrito</h2><button onClick={()=>setOpen(false)}>×</button></div>{cart.items.length===0?<p className="empty">Tu carrito está vacío.</p>:cart.items.map(i=><div className="cartItem" key={i.product.id}><span>{i.product.emoji}</span><div><b>{i.product.name}</b><small>Precio por confirmar</small></div><div className="qty"><button onClick={()=>cart.change(i.product.id,-1)}>−</button>{i.qty}<button onClick={()=>cart.change(i.product.id,1)}>+</button></div></div>)}<div className="drawerBottom"><p>Los precios se confirmarán antes de realizar el pedido.</p><button className="primary wide" disabled={!cart.items.length}>Continuar pedido</button></div></aside></>}</main>}